### ISSUE TITLE
Data Design and Database Setup

### ISSUE THREAD

**Issue by chris-arsenault** [chris-arsenault/xenergy-libations#1]

**Comment by jacob-a-hall** [comment]
I think the big question for data formatting is how we intend to handle recipe/ingredient variance. As I mentioned before, for purposes of cocktails alcohol can generally be categorized by 1) class (whisky, gin, tequila), 2) type (bourbon vs rye whisky), and 3) brand (Bulleit Bourbon vs Knob Creek Bourbon).

This variance will manifest pretty quickly. Take a very popular classic, the Negroni. You can use any of dozens of different kinds of gin, a half a dozen different kinds of sweet vermouth, but you must use Campari.

So if the initial recipe calling feature is based on user input search queries, the ideal database design would have to allow a user to input either "gin", "London Dry Gin," or "Beefeater Gin" and include the Negroni in the search results.

**Comment by chris-arsenault** [comment]
Can we come up with 4 or so classification levels?  Alcohol-or not / type / brand / sku

**Comment by jacob-a-hall** [comment]
If alcohol-or-not is basically a yes/no value to separate alcoholic from non-alcoholic ingredients in the database, then I think we need 5 classification levels:

1) Alcoholic or non-alcoholic
If non-alcoholic: 2) Ingredient type
If alcoholic:  2) Alcohol category (vodka, gin, etc.)
3) Alcohol type (Bourbon, Reposado, Dark Rum, etc.)
4) Alcohol brand
5) SKU

**Comment by chris-arsenault** [comment]
1) alcohol/dry/mixer/garnish ?

**Comment by jacob-a-hall** [comment]
Oh... hmm..

If we're going that wide, it would probably be this:

1) Ingredient type (alcohol, juice, syrup/shrub, bitters, garnish, and other)

And then each ingredient type would split into its own string of unique classifications beyond the initial type.

**Comment by jacob-a-hall** [comment]
Mixer would also be a stand alone ingredient type.

**Comment by chris-arsenault** [comment]
this part is mostly up to you, i lack the domain knowledge.  i was thinking on the lines of can you buy it in a normal store or do you have to go to a liqour store, and then is it essential to the drink

**Comment by chris-arsenault** [comment]
so i think for ingredient categories there's enough ambiguity to have an arbitrary hash of catagorizations and then maybe sku as a static field.  if we decide we need more specific stuff later we can always remap the data
